### ISSUE TITLE
Set up project board on repository

### ISSUE THREAD

**Issue by catw101** [nehCG/algorithm-lovers#6]

**Comment by nehCG** [comment]
Hi, I think I have done this last week.
Link: https://github.com/users/nehCG/projects/1

**Comment by catw101** [comment]
Please link it to your repository!

**Comment by nehCG** [comment]
Hi, it seems like the project is already linked with this repo because once you click items in the Todo list, it will direct you to the corresponding repository. And I did not find any method to link the whole project to a particular repo.

If my understanding is wrong or there is indeed a way to link it to this repo, please help me point out. Thank you!

**Comment by catw101** [comment]
Resolved!
